sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script: mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: QbE2ttq/fQf1ZZ83A/JEPflT3XZTKVdYU3uvMd/XAml7qyzqrTwI/bQJZPyIWxe/3jvSINViL4BspRWj5zTdaY/4QHKuahXUlz+JQifL0plvGGndQoZfO3yI2dCaLuKmk0NpOQW3gh22/UON4wT/k/X/KYQn+gq7e8KMz+N151o=
